### ISSUE TITLE
Update Xenbase BGI url

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-gene-mapping#10]
The Xenbase gene info files have been split by species, so now the single file has been replaced by this pair

https://fms.alliancegenome.org/download/BGI_XBXL.json.gz
https://fms.alliancegenome.org/download/BGI_XBXT.json.gz

**Comment by glass-ships** [comment]
Should this change be made in Monarch Ingest as well?

**Comment by glass-ships** [comment]
Updated in 0.1.4
