### ISSUE TITLE
Add Ensembl and UniProtKB mappings for Dog, Cow, Pig and Chicken

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-gene-mapping#18]
Happily, this is really just an expansion of what @amc-corey-cox already set up to get ENSEMBL->NCBI mappings for chicken to get the other 3 species, and then do the same to get the UniProtKB mappings as well for all four.

**Comment by kevinschaper** [comment]
Also Aspergillus, taxon ID 227321

**Comment by amc-corey-cox** [comment]
Taxon ID's: Chicken: 9031, Dog: 9615, Cow, 9913, Pig: 9823

**Comment by amc-corey-cox** [comment]
A quick search of ensembl2gene.gz did not have data for Aspergillus with taxonID 227321 or 162425 or Dictostellium with taxonID  44689. I don't think these taxons are in the enseml2gene file but I can't rule out that they are simply using a different taxonID I did not search for.
