### ISSUE TITLE
Add  UniprotKB to preferred gene mappings

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-gene-mapping#3]
We have 500k dangling edges that use UniprotKB prefixes from the go annotation edges file that need to be mapped to the correct gene id for the species. This might bring the big mapping file back, if there are no other source. 

The "big" Uniprot mapping file is at **https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/**.  Some (but not all) of the species of interest are in taxon-specific files at https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism/. Alas, this subdirectory doesn't include the following species:

- Dog (9615)
- Cow (9913)
- Pig (9823)
- Chicken (9031)
- _Aspergillus_ or rather,  _Emericella nidulans_ (227321)

Resolving these mappings could leverage NCBI gene mappings.

[Other issue tickets](https://github.com/monarch-initiative/monarch-gene-mapping/issues) are defined elsewhere in this repository for non-NCBI model organism gene identifier mappings to UniProtKB.

**Comment by kevinschaper** [comment]
I had completely forgotten, but we actually already UniprotKB mappings for HGNC, and I'm realizing that strategically, that's what we want: we'll map a UniprotKB ID to a gene if HGNC says so. 

I've also just realized that we should get a ton of uniprot mappings from the BGI files, and for some reason we were choosing to only get NCBI mappings before.

**Comment by RichardBruskiewich** [comment]
https://fms.alliancegenome.org/download/GENECROSSREFERENCE_COMBINED.tsv.gz seems to cluster xrefs for RefSeq entries. In several cases, not all, both an NCBI and Uniprot ID are given alongside the RefSeq ID.

**Comment by RichardBruskiewich** [comment]
https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/README

**Comment by RichardBruskiewich** [comment]
Just wanting to put the targets in clear view here (taken from the [Monarch Ingest Source Grid](https://docs.google.com/spreadsheets/d/1XrljI1Dk2Tg0teJSbQls5Iq_KCGXMCdyWvqAMfMgJ-M/edit#gid=0):

**HGNC:**  Human
**RGD:**  Rat

### Alliance:
- Mouse
- Zebrafish
- Frog
- Fly
- Worm
- Yeast

### NCBI:
- Dog
- Cow
- Pig
- Chicken
- Aspergillus

**Dictybase:** Dictyostelium

**Pombase:** Fission yeast

**Comment by putmantime** [comment]
Expand this mapping to include UniProt mappings to all preferred namespaces

**Comment by RichardBruskiewich** [comment]
Resolved by https://github.com/monarch-initiative/monarch-gene-mapping/pull/27
