### ISSUE TITLE
Instead of obo_converter, use the SSSOM EPM directly

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-gene-mapping#35]
For context see: https://github.com/monarch-initiative/monarch-gene-mapping/pull/34#discussion_r1416046747

```
pip install sssom
```

```
from sssom.context import get_converter
converter = get_converter()
```

@glass-ships does this work for you? This will use the correct complete and SSSOM aligned obo converter.

**Comment by glass-ships** [comment]
correct. i'll run a jenkins job now to populate the missing fields.

**Comment by glass-ships** [comment]
The file should be updated and fixed now in data.mi.org
